[project]
name = "rafi"
version = "0.1.0"
description = "Data pipeline for RAFI poultry concentration dashboard"
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

